[workspace]

members = [
    "common/certificate",
    "common/flockfile",
    "common/mqtt_client",
    "tedge",
    "tedge_config",
    "mapper/cumulocity/c8y_translator_lib",
    "mapper/dm_agent",
    "mapper/tedge_mapper",
    "mapper/thin_edge_json",
]

[profile.release]
lto = true

# opt-level = "z" # See https://doc.rust-lang.org/cargo/reference/profiles.html
# codegen-units = 1
# panic = 'abort'
