[package]
name = "c8y_http_proxy"
description = "thin-edge Cumulocity extension adding REST API support"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
c8y_api = { workspace = true }
download = { workspace = true }
http = { workspace = true }
log = { workspace = true }
mqtt_channel = { workspace = true }
tedge_actors = { workspace = true }
tedge_config = { workspace = true }
tedge_http_ext = { workspace = true }
tedge_utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[dev-dependencies]
tedge_http_ext = { workspace = true, features = [
    "test_helpers",
] }
