[package]
name = "c8y-device-management"
description = "thin-edge Cumulocity plugin for device management"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
c8y_config_manager = { workspace = true }
c8y_firmware_manager = { workspace = true }
c8y_http_proxy = { workspace = true }
c8y_log_manager = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tedge_actors = { workspace = true }
tedge_config = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_health_ext = { workspace = true }
tedge_http_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_signal_ext = { workspace = true }
tedge_timer_ext = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
