[package]
name = "tedge_file_system_ext"
description = "thin-edge extension adding file system events notitification"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
log = { workspace = true }
tedge_actors = { workspace = true }
tedge_utils = { workspace = true, features = ["fs-notify"] }
tokio = { workspace = true, features = ["macros"] }
try-traits = { workspace = true }

[dev-dependencies]
tedge_actors = { workspace = true, features = ["test-helpers"] }
tedge_test_utils = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
