[package]
name = "mqtt_channel"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1"
certificate = { path = "../certificate" }
fastrand = "1.8"
futures = "0.3"
rumqttc = "0.18"
thiserror = "1.0"
tokio = { version = "1.23", features = ["rt", "time"] }
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0"
mqtt_tests = { path = "../../tests/mqtt_tests" }
serial_test = "0.8"
