[package]
name = "mqtt_channel"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
certificate = { workspace = true }
fastrand = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
rumqttc = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }

[dev-dependencies]
anyhow = { workspace = true }
mqtt_tests = { workspace = true }
serial_test = { workspace = true }
