name: integration-test-workflow

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:

  install-and-use-amd64-github-hosted:

    runs-on: [self-hosted, Linux, ARM, offsite]

    continue-on-error: true
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Download artifact
          uses: dawidd6/action-download-artifact@v2
          # https://github.com/marketplace/actions/download-workflow-artifact
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build-workflow.yml
            workflow_conclusion: success
            branch: continuous_integration
            name: debian-packages-amd64
            path: debian-package_unpack

        - name: Download artifact
          uses: dawidd6/action-download-artifact@v2
          # https://github.com/marketplace/actions/download-workflow-artifact
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build-workflow.yml
            workflow_conclusion: success
            branch: continuous_integration
            name: examples_amd64
            path: examples

        - name: Run Smoke Test
          run: ./ci/ci_smoke_test.sh
          env:
            C8YPASS: ${{ secrets.SECRET_C8YPASS }}
            C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
            C8YTENANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICE: ${{ secrets.SECRET_C8YDEVICE }}_gh_hosted
            C8YDEVICEID: ${{ secrets.SECRET_C8YDEVICEID_GH_HOSTED }}
